import turtle
manoj = turtle.Pen()
manoj.color('red')
manoj.shape('turtle')
manoj.circle(200)
manoj.color('blue')
manoj.circle(150)
manoj.color('red')
manoj.circle(100)
manoj.circle(40)
manoj.color('blue')
manoj.circle(50)
manoj.left(180)
manoj.color('green')
manoj.circle(200)
manoj.color('yellow')
manoj.circle(150)
manoj.color('green')
manoj.circle(100)
manoj.color('yellow')
manoj.circle(50)
manoj.color('green')
manoj.circle(40)
manoj.up()
manoj.forward(100)
manoj.left(90)
